# Generated by Django 2.2.7 on 2020-10-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('userid', models.IntegerField(null=True)),
                ('storeid', models.IntegerField(null=True)),
                ('tourspotid', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('score', models.FloatField(null=True)),
            ],
        ),
    ]
