# Generated by Django 2.2.7 on 2020-10-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('temp_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('temp_username', models.CharField(max_length=50, null=True)),
                ('temp_type', models.CharField(max_length=50, null=True)),
                ('temp_typeid', models.IntegerField(null=True)),
                ('temp_title', models.CharField(max_length=200, null=True)),
                ('temp_lat', models.FloatField(max_length=10, null=True)),
                ('temp_lon', models.FloatField(max_length=10, null=True)),
            ],
        ),
    ]
