# Generated by Django 2.2.7 on 2020-10-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('orderid', models.IntegerField(null=True)),
                ('order', models.IntegerField(null=True)),
                ('contenttype', models.IntegerField(null=True)),
                ('contentid', models.IntegerField(null=True)),
                ('latitude', models.FloatField(max_length=20, null=True)),
                ('longitude', models.FloatField(max_length=20, null=True)),
            ],
        ),
    ]
